name: clock-signal
version: '20.7.11'
summary: An emulator of various 8- and 16-bit computers and consoles.
description: |
  An emulator of the Acorn Electron, Amstrad CPC, Apple II/II+/IIe and
  early Macintosh, Atari 2600 and ST, ColecoVision, Commodore Vic-20,
  MSX 1, Oric 1/Atmos, Sega Master System and Sinclair ZX80/81.

grade: devel
confinement: strict

parts:
  clock-signal:
    source: ./OSBindings/Qt
    plugin: qmake
    qt-version: qt5
    project-files: [ClockSignal.pro]
    build-packages:
      - g++
      - qt5-default
